import type { Article, PollingMetric, EconomicMetric } from "@/types";

/** Realistic seed data for design & development.
 *  Marked clearly as DEMO so it is never mixed with live records.
 *  Headlines are illustrative composites based on public reporting patterns;
 *  they are not claimed to be exact published headlines.
 */

export const SEED_POLLING: PollingMetric = {
  id: "seed-cnn-1",
  pollster: "CNN Poll of Polls",
  approval: 41.0,
  disapproval: 55.0,
  net: -14.0,
  period_label: "Latest available aggregate",
  source_url: "https://www.cnn.com/politics/polls",
  source_date: "2025-09-15T00:00:00Z",
  fetched_at: new Date().toISOString(),
  is_manual: true,
  status: "ok",
};

export const SEED_DEBT: EconomicMetric = {
  id: "seed-debt-1",
  metric_key: "treasury_debt",
  value: 35_800_000_000_000,
  value_label: "$35.8T",
  period_end: "2025-09-19",
  source: "U.S. Treasury Fiscal Data — Debt to the Penny",
  source_url: "https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/",
  source_date: "2025-09-19T00:00:00Z",
  fetched_at: new Date().toISOString(),
  status: "ok",
  metadata: {
    change_since_2025_01_20: 1_200_000_000_000,
    change_since_2017_01_20: 16_000_000_000_000,
    change_last_year: 2_100_000_000_000,
  },
};

export const SEED_GAS: EconomicMetric = {
  id: "seed-gas-1",
  metric_key: "eia_gas_regular",
  value: 3.42,
  value_label: "$3.42 / gal",
  period_end: "2025-09-15",
  source: "U.S. Energy Information Administration",
  source_url: "https://www.eia.gov/petroleum/gasdiesel/",
  source_date: "2025-09-15T00:00:00Z",
  fetched_at: new Date().toISOString(),
  status: "ok",
  metadata: {
    change_1m: 0.08,
    change_1m_pct: 2.4,
    change_1y: -0.15,
    change_1y_pct: -4.2,
    change_10y: 1.10,
    change_10y_pct: 47.4,
  },
};

export const SEED_GROCERIES: EconomicMetric = {
  id: "seed-bls-1",
  metric_key: "bls_food_at_home",
  value: 312.4,
  value_label: "CPI-U Food at Home 312.4",
  period_end: "2025-08-01",
  source: "U.S. Bureau of Labor Statistics",
  source_url: "https://www.bls.gov/cpi/",
  source_date: "2025-09-11T00:00:00Z",
  fetched_at: new Date().toISOString(),
  status: "ok",
  metadata: {
    mom: 0.3,
    yoy: 1.8,
    change_10y_pct: 28.5,
  },
};

export const SEED_ARTICLES: Article[] = [
  {
    id: "seed-1",
    headline: "Federal appeals court upholds lower court ruling against administration policy",
    normalized_headline: "federal appeals court upholds lower court ruling against administration policy",
    slug: "federal-appeals-court-upholds-ruling",
    publisher_name: "Reuters",
    publisher_domain: "reuters.com",
    canonical_url: "https://www.reuters.com/example/seed-1",
    image_url: null,
    description: "A federal appeals court on Monday upheld a lower court decision that blocked a key administration initiative.",
    summary: "A federal appellate panel affirmed a district court injunction, leaving the policy suspended pending further proceedings.",
    published_at: "2025-09-20T14:22:00Z",
    collected_at: "2025-09-20T15:00:00Z",
    article_type: "news",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.92,
    is_featured: true,
    categories: ["courts-legal"],
  },
  {
    id: "seed-2",
    headline: "New polling shows continued soft approval numbers amid economic concerns",
    normalized_headline: "new polling shows continued soft approval numbers amid economic concerns",
    slug: "polling-soft-approval-economic",
    publisher_name: "Associated Press",
    publisher_domain: "apnews.com",
    canonical_url: "https://apnews.com/example/seed-2",
    description: "The latest national survey finds the president’s job approval remaining underwater.",
    summary: "A national survey released this week shows job approval remaining below 45 percent, with economic issues cited as a primary driver.",
    published_at: "2025-09-19T18:00:00Z",
    collected_at: "2025-09-19T19:00:00Z",
    article_type: "polling",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.88,
    is_featured: false,
    categories: ["public-opinion", "economy"],
  },
  {
    id: "seed-3",
    headline: "Inspectors general report raises ethics questions over agency contracting",
    normalized_headline: "inspectors general report raises ethics questions over agency contracting",
    slug: "ig-report-ethics-contracting",
    publisher_name: "The Washington Post",
    publisher_domain: "washingtonpost.com",
    canonical_url: "https://www.washingtonpost.com/example/seed-3",
    description: "A newly released inspector general report identifies potential conflicts in several major contracts.",
    summary: "An inspector general examination found procedural irregularities and potential conflicts of interest in a set of large federal contracts.",
    published_at: "2025-09-18T12:30:00Z",
    collected_at: "2025-09-18T13:00:00Z",
    article_type: "investigation",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.95,
    is_featured: false,
    categories: ["ethics-government", "investigations"],
  },
  {
    id: "seed-4",
    headline: "Markets react to latest trade and tariff announcements",
    normalized_headline: "markets react to latest trade and tariff announcements",
    slug: "markets-react-trade-tariffs",
    publisher_name: "Bloomberg",
    publisher_domain: "bloomberg.com",
    canonical_url: "https://www.bloomberg.com/example/seed-4",
    description: "Equity and bond markets moved sharply after the White House detailed new tariff measures.",
    summary: "Major indices declined following the announcement of expanded tariffs, with analysts citing uncertainty over implementation timelines.",
    published_at: "2025-09-17T21:00:00Z",
    collected_at: "2025-09-17T22:00:00Z",
    article_type: "news",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.81,
    is_featured: false,
    categories: ["economy", "business", "foreign-policy"],
  },
  {
    id: "seed-5",
    headline: "Senate committee schedules oversight hearing on immigration enforcement",
    normalized_headline: "senate committee schedules oversight hearing on immigration enforcement",
    slug: "senate-oversight-immigration",
    publisher_name: "Politico",
    publisher_domain: "politico.com",
    canonical_url: "https://www.politico.com/example/seed-5",
    description: "The Senate Judiciary Committee announced a hearing focused on recent enforcement actions.",
    summary: "Lawmakers from both parties will question administration officials about recent immigration enforcement policy and resource allocation.",
    published_at: "2025-09-16T16:45:00Z",
    collected_at: "2025-09-16T17:00:00Z",
    article_type: "news",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.78,
    is_featured: false,
    categories: ["immigration", "congress"],
  },
  {
    id: "seed-6",
    headline: "Fact check: Claims about unemployment numbers draw scrutiny",
    normalized_headline: "fact check claims about unemployment numbers draw scrutiny",
    slug: "fact-check-unemployment-claims",
    publisher_name: "CNN",
    publisher_domain: "cnn.com",
    canonical_url: "https://www.cnn.com/example/seed-6",
    description: "Independent review finds several recent statements about the unemployment rate do not align with BLS data.",
    summary: "A review of recent public statements against Bureau of Labor Statistics data found multiple claims that overstated improvement in the unemployment rate.",
    published_at: "2025-09-15T11:00:00Z",
    collected_at: "2025-09-15T12:00:00Z",
    article_type: "fact-check",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.97,
    is_featured: false,
    categories: ["fact-checks", "economy"],
  },
  {
    id: "seed-7",
    headline: "Former officials describe internal disagreements over foreign policy approach",
    normalized_headline: "former officials describe internal disagreements over foreign policy approach",
    slug: "former-officials-foreign-policy",
    publisher_name: "The New York Times",
    publisher_domain: "nytimes.com",
    canonical_url: "https://www.nytimes.com/example/seed-7",
    description: "Accounts from former administration aides portray significant internal friction on several diplomatic initiatives.",
    summary: "Multiple former officials described competing factions and delayed decision-making on key foreign-policy files during the early months of the term.",
    published_at: "2025-09-14T09:15:00Z",
    collected_at: "2025-09-14T10:00:00Z",
    article_type: "analysis",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.86,
    is_featured: false,
    categories: ["foreign-policy", "administration"],
  },
  {
    id: "seed-8",
    headline: "State attorneys general file coordinated challenge to new federal rule",
    normalized_headline: "state attorneys general file coordinated challenge to new federal rule",
    slug: "ags-challenge-federal-rule",
    publisher_name: "Associated Press",
    publisher_domain: "apnews.com",
    canonical_url: "https://apnews.com/example/seed-8",
    description: "A coalition of state attorneys general sued to block a recently finalized federal regulation.",
    summary: "Attorneys general from more than a dozen states filed suit arguing the new rule exceeds statutory authority and will impose significant costs.",
    published_at: "2025-09-13T20:00:00Z",
    collected_at: "2025-09-13T21:00:00Z",
    article_type: "legal",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.91,
    is_featured: false,
    categories: ["courts-legal", "policy"],
  },
  {
    id: "seed-9",
    headline: "Editorial: The cost of policy uncertainty",
    normalized_headline: "editorial the cost of policy uncertainty",
    slug: "editorial-policy-uncertainty",
    publisher_name: "The Wall Street Journal",
    publisher_domain: "wsj.com",
    canonical_url: "https://www.wsj.com/example/seed-9",
    description: "The editorial board argues that repeated policy reversals are undermining business investment.",
    summary: "An editorial contends that frequent shifts in regulatory and trade policy are creating measurable drag on capital expenditure plans.",
    published_at: "2025-09-12T14:00:00Z",
    collected_at: "2025-09-12T15:00:00Z",
    article_type: "editorial",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.84,
    is_featured: false,
    categories: ["opinion-editorial", "business"],
  },
  {
    id: "seed-10",
    headline: "House panel advances subpoenas related to prior administration contacts",
    normalized_headline: "house panel advances subpoenas related to prior administration contacts",
    slug: "house-subpoenas-prior-contacts",
    publisher_name: "NBC News",
    publisher_domain: "nbcnews.com",
    canonical_url: "https://www.nbcnews.com/example/seed-10",
    description: "A House committee voted along party lines to issue subpoenas in an ongoing investigation.",
    summary: "The committee approved a package of subpoenas seeking records and testimony concerning contacts between former officials and private entities.",
    published_at: "2025-09-11T19:30:00Z",
    collected_at: "2025-09-11T20:00:00Z",
    article_type: "news",
    term: "second",
    qualification: "QUALIFY",
    qualification_confidence: 0.89,
    is_featured: false,
    categories: ["congress", "investigations"],
  },
];

export const SEED_ARCHIVE_COUNT = {
  total: 87421,
  today: 47,
  thisWeek: 312,
  thisMonth: 1489,
};
